modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/wilkcraft/RaftWorld/issues"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

displayURL="https://github.com/wilkcraft/RaftWorld"

#logoFile="examplemod.png" #optional

#credits="" #optional

authors="Wilkcraft"

description='''
Start on a tiny raft in an endless ocean. Survive and rebuild the world.
'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
